#!/usr/bin/env node
// Generates deterministic seed SQL for the CRM demo app's D1 database.
// Derives `reps` directly from hr-app's already-generated seed data (same
// ids/emails/manager hierarchy as hr-app's employees and FlareID's users),
// then generates companies/contacts/deals/activities with @faker-js/faker.
//
// Usage: node shared/seed/generate-seed.mjs > api/migrations/0002_seed.sql

import { faker } from "@faker-js/faker";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

faker.seed(142); // deterministic output across runs

const __dirname = dirname(fileURLToPath(import.meta.url));
const HR_SEED_PATH = resolve(__dirname, "../../../hr-app/api/migrations/0002_seed.sql");
const OUT_PATH = resolve(__dirname, "../../api/migrations/0002_seed.sql");

const hrSeedSql = readFileSync(HR_SEED_PATH, "utf8");

function sqlStr(value) {
  if (value === null || value === undefined) return "NULL";
  return `'${String(value).replace(/'/g, "''")}'`;
}
function isoDate(d) {
  return d.toISOString().slice(0, 10);
}

const SQL_STRING = "'((?:[^']|'')*)'";
function unescapeSql(value) {
  return value.replace(/''/g, "'");
}

// --- Parse departments (to weight deal/company ownership toward Sales) ---
const departments = new Map(); // id -> name
for (const match of hrSeedSql.matchAll(
  new RegExp(`INSERT INTO departments \\(id, name, division, cost_center\\) VALUES \\((\\d+), ${SQL_STRING}`, "g")
)) {
  departments.set(Number(match[1]), unescapeSql(match[2]));
}

// --- Parse employees -> reps (id, name, email, job_title, department_id, manager_id) ---
const employeeRowRegex = new RegExp(
  `INSERT INTO employees \\([^)]*\\) VALUES \\((\\d+), ${SQL_STRING}, ${SQL_STRING}, ${SQL_STRING}, ${SQL_STRING}, ${SQL_STRING}, (\\d+), (NULL|\\d+),`,
  "g"
);

const reps = [];
for (const match of hrSeedSql.matchAll(employeeRowRegex)) {
  const [, id, , firstName, lastName, email, jobTitle, departmentId, managerId] = match;
  reps.push({
    id: Number(id),
    firstName: unescapeSql(firstName),
    lastName: unescapeSql(lastName),
    // hr-app's own emails have since been renamed to @company.com in a later
    // migration - match current reality rather than the original seed text.
    email: unescapeSql(email).replace(/@aihorizon-demo\.com$/, "@company.com"),
    jobTitle: unescapeSql(jobTitle),
    departmentId: Number(departmentId),
    managerId: managerId === "NULL" ? null : Number(managerId),
  });
}

if (reps.length === 0) {
  console.error(`No employees parsed from ${HR_SEED_PATH} - has the hr-app seed been generated?`);
  process.exit(1);
}

const statements = [];
statements.push("-- Auto-generated by shared/seed/generate-seed.mjs. Do not edit by hand.");

for (const r of reps) {
  statements.push(
    `INSERT INTO reps (id, first_name, last_name, email, job_title, manager_id) VALUES (${r.id}, ${sqlStr(r.firstName)}, ${sqlStr(r.lastName)}, ${sqlStr(r.email)}, ${sqlStr(r.jobTitle)}, ${r.managerId ?? "NULL"});`
  );
}

// Weight ownership toward the Sales department (id 2 in hr-app's seed), but
// let anyone own an account/deal occasionally - a VP or even an engineer
// sponsoring a strategic deal is realistic enough for a demo.
const ownerPool = [];
for (const r of reps) {
  const weight = r.departmentId === 2 ? 6 : 1;
  for (let i = 0; i < weight; i++) ownerPool.push(r.id);
}
function pickOwner() {
  return faker.helpers.arrayElement(ownerPool);
}

const INDUSTRIES = ["Software", "Manufacturing", "Retail", "Healthcare", "Financial Services", "Logistics", "Media", "Energy"];
const STAGES = ["prospecting", "qualification", "proposal", "negotiation", "closed_won", "closed_lost"];
const STAGE_WEIGHTS = [
  { value: "prospecting", weight: 3 },
  { value: "qualification", weight: 3 },
  { value: "proposal", weight: 2 },
  { value: "negotiation", weight: 2 },
  { value: "closed_won", weight: 3 },
  { value: "closed_lost", weight: 2 },
];
const ACTIVITY_TYPES = ["call", "email", "meeting", "note"];

const COMPANY_COUNT = 25;
let companyId = 1;
let contactId = 1;
let dealId = 1;
let activityId = 1;

for (let i = 0; i < COMPANY_COUNT; i++) {
  const companyName = faker.company.name();
  const ownerId = pickOwner();
  const domain = faker.internet.domainName();
  statements.push(
    `INSERT INTO companies (id, name, industry, website, address, owner_id) VALUES (${companyId}, ${sqlStr(companyName)}, ${sqlStr(faker.helpers.arrayElement(INDUSTRIES))}, ${sqlStr(`https://${domain}`)}, ${sqlStr(`${faker.location.streetAddress()}, ${faker.location.city()}, ${faker.location.state({ abbreviated: true })} ${faker.location.zipCode()}`)}, ${ownerId});`
  );

  const contactCount = faker.number.int({ min: 1, max: 3 });
  const companyContacts = [];
  for (let c = 0; c < contactCount; c++) {
    const firstName = faker.person.firstName();
    const lastName = faker.person.lastName();
    const contact = {
      id: contactId++,
      firstName,
      lastName,
      email: faker.internet.email({ firstName, lastName, provider: domain }).toLowerCase(),
      phone: faker.phone.number({ style: "national" }),
      title: faker.person.jobTitle(),
    };
    companyContacts.push(contact);
    statements.push(
      `INSERT INTO contacts (id, company_id, first_name, last_name, email, phone, title) VALUES (${contact.id}, ${companyId}, ${sqlStr(contact.firstName)}, ${sqlStr(contact.lastName)}, ${sqlStr(contact.email)}, ${sqlStr(contact.phone)}, ${sqlStr(contact.title)});`
    );
  }

  const dealCount = faker.number.int({ min: 1, max: 3 });
  for (let d = 0; d < dealCount; d++) {
    const dealOwnerId = faker.datatype.boolean(0.8) ? ownerId : pickOwner();
    const contact = faker.helpers.arrayElement(companyContacts);
    const stage = faker.helpers.weightedArrayElement(STAGE_WEIGHTS);
    const createdAt = faker.date.between({ from: "2025-01-01", to: "2026-06-01" });
    const closeDate = new Date(createdAt);
    closeDate.setDate(closeDate.getDate() + faker.number.int({ min: 20, max: 150 }));
    const deal = {
      id: dealId++,
      name: `${companyName} - ${faker.commerce.productName()}`,
      stage,
      value: faker.number.int({ min: 8000, max: 250000 }),
    };
    statements.push(
      `INSERT INTO deals (id, company_id, contact_id, name, stage, value, close_date, owner_id, created_at, updated_at) VALUES (${deal.id}, ${companyId}, ${contact.id}, ${sqlStr(deal.name)}, ${sqlStr(deal.stage)}, ${deal.value}, ${sqlStr(isoDate(closeDate))}, ${dealOwnerId}, ${sqlStr(createdAt.toISOString())}, ${sqlStr(createdAt.toISOString())});`
    );

    const activityCount = faker.number.int({ min: 1, max: 4 });
    for (let a = 0; a < activityCount; a++) {
      const activityDate = faker.date.between({ from: createdAt, to: "2026-06-01" });
      statements.push(
        `INSERT INTO activities (id, deal_id, rep_id, type, notes, activity_date) VALUES (${activityId++}, ${deal.id}, ${dealOwnerId}, ${sqlStr(faker.helpers.arrayElement(ACTIVITY_TYPES))}, ${sqlStr(faker.helpers.arrayElement([
          "Discovery call - discussed budget and timeline.",
          "Sent follow-up proposal with pricing tiers.",
          "Met with stakeholders to review contract terms.",
          "Left voicemail, no response yet.",
          "Demo went well, moving to procurement review.",
        ]))}, ${sqlStr(isoDate(activityDate))});`
      );
    }
  }

  companyId++;
}

const sql = statements.join("\n") + "\n";
writeFileSync(OUT_PATH, sql, "utf8");
console.log(`Wrote ${statements.length} statements (${reps.length} reps, ${COMPANY_COUNT} companies) to ${OUT_PATH}`);
