#!/usr/bin/env node
// Generates deterministic seed SQL for the HR demo app's D1 database.
// Usage: node shared/seed/generate-seed.mjs > api/migrations/0002_seed.sql

import { faker } from "@faker-js/faker";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

faker.seed(42); // deterministic output across runs

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(__dirname, "../../api/migrations/0002_seed.sql");

const DEPARTMENTS = [
  { name: "Engineering", division: "Product & Technology", cost_center: "CC-100" },
  { name: "Sales", division: "Go To Market", cost_center: "CC-200" },
  { name: "Marketing", division: "Go To Market", cost_center: "CC-210" },
  { name: "People", division: "Operations", cost_center: "CC-300" },
  { name: "Finance", division: "Operations", cost_center: "CC-310" },
];

const TITLES_BY_DEPT = {
  Engineering: ["Software Engineer", "Senior Software Engineer", "Staff Engineer", "Engineering Manager"],
  Sales: ["Account Executive", "Sales Development Rep", "Solutions Engineer", "Sales Manager"],
  Marketing: ["Marketing Manager", "Content Strategist", "Demand Gen Specialist", "Product Marketing Manager"],
  People: ["HR Business Partner", "Recruiter", "People Operations Analyst", "HR Manager"],
  Finance: ["Financial Analyst", "Accountant", "Revenue Analyst", "Finance Manager"],
};

const LOCATIONS = ["Austin, TX", "New York, NY", "San Francisco, CA", "Remote - US", "London, UK"];

function sqlStr(value) {
  if (value === null || value === undefined) return "NULL";
  return `'${String(value).replace(/'/g, "''")}'`;
}

function isoDate(d) {
  return d.toISOString().slice(0, 10);
}

const statements = [];
statements.push("-- Auto-generated by shared/seed/generate-seed.mjs. Do not edit by hand.");

// 1. Departments
DEPARTMENTS.forEach((dept, i) => {
  statements.push(
    `INSERT INTO departments (id, name, division, cost_center) VALUES (${i + 1}, ${sqlStr(dept.name)}, ${sqlStr(dept.division)}, ${sqlStr(dept.cost_center)});`
  );
});

// 2. Employees: 1 CEO, 5 department heads (report to CEO), 24 ICs (report to their dept head)
const employees = [];
const usedEmails = new Set();
let empId = 1;

function makeEmail(firstName, lastName) {
  const base = `${firstName}.${lastName}`
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "") // strip accents
    .replace(/[^a-z0-9.]/g, "");
  let email = `${base}@company.com`;
  let suffix = 2;
  // Only disambiguate on an actual collision (rare with 30 random names) -
  // no cosmetic trailing numbers on every address.
  while (usedEmails.has(email)) {
    email = `${base}${suffix}@company.com`;
    suffix++;
  }
  usedEmails.add(email);
  return email;
}

function makeEmployee({ deptId, jobTitle, managerId, isHead = false }) {
  const firstName = faker.person.firstName();
  const lastName = faker.person.lastName();
  const email = makeEmail(firstName, lastName);
  const hireDate = faker.date.between({ from: "2016-01-01", to: "2024-06-01" });
  const employee = {
    id: empId++,
    employee_number: `E${String(empId - 1).padStart(4, "0")}`,
    first_name: firstName,
    last_name: lastName,
    email,
    job_title: jobTitle,
    department_id: deptId,
    manager_id: managerId,
    hire_date: isoDate(hireDate),
    employment_status: faker.helpers.weightedArrayElement([
      { value: "active", weight: 9 },
      { value: "on_leave", weight: 1 },
    ]),
    employment_type: faker.helpers.weightedArrayElement([
      { value: "full_time", weight: 9 },
      { value: "contractor", weight: 1 },
    ]),
    location: faker.helpers.arrayElement(LOCATIONS),
    photo_url: null,
    isHead,
  };
  employees.push(employee);
  return employee;
}

const ceo = makeEmployee({ deptId: 1, jobTitle: "Chief Executive Officer", managerId: null, isHead: true });

const heads = DEPARTMENTS.map((dept, i) =>
  makeEmployee({
    deptId: i + 1,
    jobTitle: `VP of ${dept.name}`,
    managerId: ceo.id,
    isHead: true,
  })
);

// 24 remaining ICs spread across departments, reporting to their department head
for (let i = 0; i < 24; i++) {
  const deptIndex = i % DEPARTMENTS.length;
  const dept = DEPARTMENTS[deptIndex];
  const head = heads[deptIndex];
  const titles = TITLES_BY_DEPT[dept.name];
  makeEmployee({
    deptId: deptIndex + 1,
    jobTitle: faker.helpers.arrayElement(titles),
    managerId: head.id,
  });
}

for (const e of employees) {
  statements.push(
    `INSERT INTO employees (id, employee_number, first_name, last_name, email, job_title, department_id, manager_id, hire_date, employment_status, employment_type, location, photo_url) VALUES (${e.id}, ${sqlStr(e.employee_number)}, ${sqlStr(e.first_name)}, ${sqlStr(e.last_name)}, ${sqlStr(e.email)}, ${sqlStr(e.job_title)}, ${e.department_id}, ${e.manager_id ?? "NULL"}, ${sqlStr(e.hire_date)}, ${sqlStr(e.employment_status)}, ${sqlStr(e.employment_type)}, ${sqlStr(e.location)}, ${sqlStr(e.photo_url)});`
  );
}

// 3. Compensation history: one hire record + one raise for most employees
let compId = 1;
for (const e of employees) {
  const baseSalary = e.isHead
    ? faker.number.int({ min: 165000, max: 240000 })
    : faker.number.int({ min: 75000, max: 145000 });
  statements.push(
    `INSERT INTO compensation_history (id, employee_id, effective_date, base_salary, currency, bonus_target_pct, change_reason) VALUES (${compId++}, ${e.id}, ${sqlStr(e.hire_date)}, ${baseSalary}, 'USD', ${e.isHead ? 20 : 10}, 'New hire offer');`
  );
  if (faker.datatype.boolean(0.6)) {
    const raise = Math.round((baseSalary * faker.number.float({ min: 1.03, max: 1.12 })) / 100) * 100;
    const raiseDate = faker.date.between({ from: e.hire_date, to: "2025-06-01" });
    statements.push(
      `INSERT INTO compensation_history (id, employee_id, effective_date, base_salary, currency, bonus_target_pct, change_reason) VALUES (${compId++}, ${e.id}, ${sqlStr(isoDate(raiseDate))}, ${raise}, 'USD', ${e.isHead ? 20 : 10}, 'Annual merit increase');`
    );
  }
}

// 4. Time-off balances (one row per employee)
for (const e of employees) {
  statements.push(
    `INSERT INTO time_off_balances (employee_id, vacation_days_remaining, sick_days_remaining, updated_at) VALUES (${e.id}, ${faker.number.int({ min: 0, max: 20 })}, ${faker.number.int({ min: 0, max: 10 })}, ${sqlStr(isoDate(new Date()))});`
  );
}

// 5. Time-off requests: 1-3 per employee
let reqId = 1;
for (const e of employees) {
  const count = faker.number.int({ min: 1, max: 3 });
  for (let i = 0; i < count; i++) {
    const start = faker.date.between({ from: "2025-01-01", to: "2026-06-01" });
    const end = new Date(start);
    end.setDate(end.getDate() + faker.number.int({ min: 1, max: 5 }));
    statements.push(
      `INSERT INTO time_off_requests (id, employee_id, type, start_date, end_date, status, requested_at) VALUES (${reqId++}, ${e.id}, ${sqlStr(faker.helpers.arrayElement(["vacation", "sick", "personal"]))}, ${sqlStr(isoDate(start))}, ${sqlStr(isoDate(end))}, ${sqlStr(faker.helpers.arrayElement(["pending", "approved", "approved", "denied"]))}, ${sqlStr(isoDate(faker.date.recent({ days: 60, refDate: start })))});`
    );
  }
}

// 6. Performance reviews: one review per employee, reviewed by their manager (CEO reviews self-report N/A -> skip)
let reviewId = 1;
for (const e of employees) {
  if (!e.manager_id) continue;
  statements.push(
    `INSERT INTO performance_reviews (id, employee_id, reviewer_id, review_period, rating, summary, review_date) VALUES (${reviewId++}, ${e.id}, ${e.manager_id}, '2025 H1', ${faker.number.int({ min: 3, max: 5 })}, ${sqlStr(faker.helpers.arrayElement([
      "Consistently exceeds expectations and mentors teammates effectively.",
      "Meets expectations with solid, reliable delivery this period.",
      "Strong technical contributions; keep building stakeholder communication.",
      "Exceeded goals for the half and took on additional scope successfully.",
    ]))}, ${sqlStr("2025-06-15")});`
  );
}

// 7. Benefits enrollments: medical + dental + vision + 401k for most employees
let benefitId = 1;
const PLANS = ["medical", "dental", "vision", "401k"];
for (const e of employees) {
  for (const plan of PLANS) {
    if (plan !== "medical" && faker.datatype.boolean(0.25)) continue; // most opt into all, some skip optional ones
    const coverage =
      plan === "401k"
        ? `${faker.number.int({ min: 3, max: 6 })}% contribution`
        : faker.helpers.arrayElement(["Employee Only", "Employee + Spouse", "Family"]);
    statements.push(
      `INSERT INTO benefits_enrollments (id, employee_id, plan_name, coverage_level, enrollment_date) VALUES (${benefitId++}, ${e.id}, ${sqlStr(plan)}, ${sqlStr(coverage)}, ${sqlStr(e.hire_date)});`
    );
  }
}

const sql = statements.join("\n") + "\n";
writeFileSync(OUT_PATH, sql, "utf8");
console.log(`Wrote ${statements.length} statements to ${OUT_PATH}`);
