#!/usr/bin/env node
// Derives FlareID's demo users + groups directly from hr-app's already-generated
// seed data, so the same 30 people exist as both HR employees and IdP accounts
// with matching UPNs (emails) out of the box - no manual identity mapping needed
// for the happy path. Departments become flat IdP groups.
//
// Also derives 0011_seed_hr_attributes.sql, which fills in each seeded user's
// HR attributes (job title, department, manager, employee number, hire date,
// employment status/type, location) to match their hr-app employee record.
// This is a stand-in for real SCIM provisioning FROM hr-app (see ROADMAP.md -
// hr-app should eventually own identity and push these via SCIM instead).
//
// Usage: node scripts/generate-seed.mjs

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const HR_SEED_PATH = resolve(__dirname, "../../hr-app/api/migrations/0002_seed.sql");
const OUT_PATH = resolve(__dirname, "../migrations/0002_seed.sql");
const HR_ATTRIBUTES_OUT_PATH = resolve(__dirname, "../migrations/0012_seed_hr_attributes.sql");
const DEFAULT_PASSWORD = "Savetheinternet!1"; // Demo-only. Real deployments should force reset on first login.
const PBKDF2_ITERATIONS = 100_000;

const hrSeedSql = readFileSync(HR_SEED_PATH, "utf8");

function sqlStr(value) {
  if (value === null || value === undefined) return "NULL";
  return `'${String(value).replace(/'/g, "''")}'`;
}

// A SQL single-quoted string literal, with '' as the escape for a literal quote.
const SQL_STRING = "'((?:[^']|'')*)'";

function unescapeSql(value) {
  return value.replace(/''/g, "'");
}

// --- Parse departments ---
const departments = new Map(); // id -> name
for (const match of hrSeedSql.matchAll(
  new RegExp(`INSERT INTO departments \\(id, name, division, cost_center\\) VALUES \\((\\d+), ${SQL_STRING}`, "g")
)) {
  departments.set(Number(match[1]), unescapeSql(match[2]));
}

// --- Parse employees (full HR attribute set) ---
// Column order in hr-app: id, employee_number, first_name, last_name, email,
// job_title, department_id, manager_id, hire_date, employment_status,
// employment_type, location, photo_url.
const employeeRowRegex = new RegExp(
  `INSERT INTO employees \\([^)]*\\) VALUES \\((\\d+), ${SQL_STRING}, ${SQL_STRING}, ${SQL_STRING}, ${SQL_STRING}, ${SQL_STRING}, (\\d+), (NULL|\\d+), ${SQL_STRING}, ${SQL_STRING}, ${SQL_STRING}, ${SQL_STRING},`,
  "g"
);

const employees = [];
for (const match of hrSeedSql.matchAll(employeeRowRegex)) {
  const [
    ,
    id,
    employeeNumber,
    firstName,
    lastName,
    email,
    jobTitle,
    departmentId,
    managerId,
    hireDate,
    employmentStatus,
    employmentType,
    location,
  ] = match;
  employees.push({
    id: Number(id),
    employeeNumber: unescapeSql(employeeNumber),
    firstName: unescapeSql(firstName),
    lastName: unescapeSql(lastName),
    email: unescapeSql(email),
    jobTitle: unescapeSql(jobTitle),
    departmentId: Number(departmentId),
    managerId: managerId === "NULL" ? null : Number(managerId),
    hireDate: unescapeSql(hireDate),
    employmentStatus: unescapeSql(employmentStatus),
    employmentType: unescapeSql(employmentType),
    location: unescapeSql(location),
  });
}

if (employees.length === 0) {
  console.error(`No employees parsed from ${HR_SEED_PATH} - has the hr-app seed been generated?`);
  process.exit(1);
}

// --- Compute a single shared PBKDF2 hash for the default demo password ---
// (matches src/lib/password.ts exactly: PBKDF2-SHA256, hex-encoded)
function toHex(bytes) {
  return [...new Uint8Array(bytes)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

async function hashPassword(password, salt, iterations) {
  const keyMaterial = await crypto.subtle.importKey("raw", new TextEncoder().encode(password), "PBKDF2", false, [
    "deriveBits",
  ]);
  const derived = await crypto.subtle.deriveBits({ name: "PBKDF2", salt, iterations, hash: "SHA-256" }, keyMaterial, 256);
  return toHex(derived);
}

const statements = [];
statements.push("-- Auto-generated by scripts/generate-seed.mjs. Do not edit by hand.");
statements.push(`-- Default password for every seeded user: ${DEFAULT_PASSWORD} (demo only)`);

// --- Groups: one per hr-app department ---
const departmentIdToGroupId = new Map();
let groupId = 1;
for (const [deptId, name] of departments) {
  departmentIdToGroupId.set(deptId, groupId);
  statements.push(
    `INSERT INTO groups (id, name, description) VALUES (${groupId}, ${sqlStr(name)}, ${sqlStr(`Everyone in the ${name} department`)});`
  );
  groupId++;
}

// --- Users ---
// Note: flareid user ids are assigned 1..N in the same order hr-app assigned
// employee ids, so a given employee's `id` also happens to be their matching
// flareid user's `id` here - relied on below to resolve manager_id.
let userId = 1;
for (const employee of employees) {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const saltHex = toHex(salt);
  const hashHex = await hashPassword(DEFAULT_PASSWORD, salt, PBKDF2_ITERATIONS);

  const upn = employee.email;
  const displayName = `${employee.firstName} ${employee.lastName}`;
  const isAdmin = 0; // legacy/unused column - the real Super Admin is the dedicated admin@<domain> account seeded separately

  statements.push(
    `INSERT INTO users (id, upn, display_name, password_hash, password_salt, password_iterations, is_admin, created_at, updated_at) VALUES (${userId}, ${sqlStr(upn)}, ${sqlStr(displayName)}, ${sqlStr(hashHex)}, ${sqlStr(saltHex)}, ${PBKDF2_ITERATIONS}, ${isAdmin}, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);`
  );

  const groupIdForUser = departmentIdToGroupId.get(employee.departmentId);
  if (groupIdForUser) {
    statements.push(`INSERT INTO group_members (group_id, user_id) VALUES (${groupIdForUser}, ${userId});`);
  }

  userId++;
}

const sql = statements.join("\n") + "\n";
writeFileSync(OUT_PATH, sql, "utf8");
console.log(`Wrote ${statements.length} statements (${employees.length} users, ${departments.size} groups) to ${OUT_PATH}`);
console.log(`Default password for all seeded users: ${DEFAULT_PASSWORD}`);

// --- HR attributes migration (runs after 0006 adds the columns) ---
const hrAttrStatements = [
  "-- Auto-generated by scripts/generate-seed.mjs. Do not edit by hand.",
  "-- Fills in HR attributes for the seeded users to match their hr-app employee record.",
  "-- Stand-in for real SCIM provisioning from hr-app (see ROADMAP.md).",
];

for (const employee of employees) {
  const departmentName = departments.get(employee.departmentId) ?? "";
  hrAttrStatements.push(
    `UPDATE users SET job_title = ${sqlStr(employee.jobTitle)}, department = ${sqlStr(departmentName)}, employee_number = ${sqlStr(employee.employeeNumber)}, hire_date = ${sqlStr(employee.hireDate)}, employment_status = ${sqlStr(employee.employmentStatus)}, employment_type = ${sqlStr(employee.employmentType)}, location = ${sqlStr(employee.location)}${
      employee.managerId ? `, manager_external_id = (SELECT external_id FROM users WHERE id = ${employee.managerId})` : ""
    } WHERE id = ${employee.id};`
  );
}

writeFileSync(HR_ATTRIBUTES_OUT_PATH, hrAttrStatements.join("\n") + "\n", "utf8");
console.log(`Wrote ${hrAttrStatements.length - 3} HR attribute UPDATE statements to ${HR_ATTRIBUTES_OUT_PATH}`);
