#!/usr/bin/env node
// Generates deterministic seed SQL for Nexus (internal wiki) demo app's D1
// database. Derives `users` directly from hr-app's already-generated seed
// data (same ids/emails/manager hierarchy), then generates spaces (some
// restricted) and a page tree with version history via @faker-js/faker.
//
// Usage: node shared/seed/generate-seed.mjs > api/migrations/0002_seed.sql

import { faker } from "@faker-js/faker";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

faker.seed(342); // deterministic output across runs

const __dirname = dirname(fileURLToPath(import.meta.url));
const HR_SEED_PATH = resolve(__dirname, "../../../hr-app/api/migrations/0002_seed.sql");
const OUT_PATH = resolve(__dirname, "../../api/migrations/0002_seed.sql");

const hrSeedSql = readFileSync(HR_SEED_PATH, "utf8");

function sqlStr(value) {
  if (value === null || value === undefined) return "NULL";
  return `'${String(value).replace(/'/g, "''")}'`;
}

const SQL_STRING = "'((?:[^']|'')*)'";
function unescapeSql(value) {
  return value.replace(/''/g, "'");
}

// --- Parse employees -> users (keeping department_id, to scope space membership) ---
const employeeRowRegex = new RegExp(
  `INSERT INTO employees \\([^)]*\\) VALUES \\((\\d+), ${SQL_STRING}, ${SQL_STRING}, ${SQL_STRING}, ${SQL_STRING}, ${SQL_STRING}, (\\d+), (NULL|\\d+),`,
  "g"
);

const users = [];
for (const match of hrSeedSql.matchAll(employeeRowRegex)) {
  const [, id, , firstName, lastName, email, jobTitle, departmentId, managerId] = match;
  users.push({
    id: Number(id),
    firstName: unescapeSql(firstName),
    lastName: unescapeSql(lastName),
    email: unescapeSql(email).replace(/@aihorizon-demo\.com$/, "@company.com"),
    jobTitle: unescapeSql(jobTitle),
    departmentId: Number(departmentId),
    managerId: managerId === "NULL" ? null : Number(managerId),
  });
}

if (users.length === 0) {
  console.error(`No employees parsed from ${HR_SEED_PATH} - has the hr-app seed been generated?`);
  process.exit(1);
}

const ceo = users.find((u) => u.managerId === null);
const statements = [];
statements.push("-- Auto-generated by shared/seed/generate-seed.mjs. Do not edit by hand.");

for (const u of users) {
  statements.push(
    `INSERT INTO users (id, first_name, last_name, email, job_title, manager_id) VALUES (${u.id}, ${sqlStr(u.firstName)}, ${sqlStr(u.lastName)}, ${sqlStr(u.email)}, ${sqlStr(u.jobTitle)}, ${u.managerId ?? "NULL"});`
  );
}

// department_id -> hr-app's department name (kept in sync manually - small, fixed list)
const DEPARTMENTS = { 1: "Engineering", 2: "Sales", 3: "Marketing", 4: "People", 5: "Finance" };

const SPACES = [
  { name: "General", description: "Company-wide announcements and how-tos.", restricted: false, deptId: null },
  { name: "Engineering", description: "Engineering team documentation.", restricted: false, deptId: 1 },
  { name: "Sales", description: "Sales playbooks and enablement.", restricted: false, deptId: 2 },
  { name: "Marketing", description: "Brand guidelines and campaign docs.", restricted: false, deptId: 3 },
  { name: "People (HR)", description: "HR policies and people processes - restricted to the People team.", restricted: true, deptId: 4 },
  { name: "Finance", description: "Financial policies and reporting - restricted to the Finance team.", restricted: true, deptId: 5 },
  { name: "Executive", description: "Leadership-only strategy and planning docs.", restricted: true, deptId: null },
];

const PAGE_TITLES = [
  "Onboarding Guide",
  "Team Processes",
  "Meeting Cadence",
  "Tools We Use",
  "FAQ",
  "Style Guide",
  "Runbook",
  "Roadmap Overview",
  "Glossary",
  "Escalation Policy",
  "Vendor List",
  "Quarterly Planning",
];

let spaceId = 1;
let pageId = 1;
let versionId = 1;

for (const space of SPACES) {
  const deptMembers = space.deptId ? users.filter((u) => u.departmentId === space.deptId) : [];
  const ownerId = space.name === "Executive" ? ceo.id : deptMembers[0]?.id ?? ceo.id;

  statements.push(
    `INSERT INTO spaces (id, name, description, is_restricted, owner_id, created_at) VALUES (${spaceId}, ${sqlStr(space.name)}, ${sqlStr(space.description)}, ${space.restricted ? 1 : 0}, ${ownerId}, ${sqlStr(faker.date.past({ years: 2 }).toISOString())});`
  );

  if (space.restricted) {
    // Members: the whole matching department, or (for Executive) the CEO + every VP (managed directly by the CEO).
    const members = space.name === "Executive" ? users.filter((u) => u.managerId === ceo.id) : deptMembers;
    const memberIds = new Set([ownerId, ...members.map((m) => m.id)]);
    for (const id of memberIds) {
      statements.push(`INSERT INTO space_members (space_id, user_id) VALUES (${spaceId}, ${id});`);
    }
  }

  const contributors = deptMembers.length > 0 ? deptMembers : space.name === "Executive" ? users.filter((u) => u.managerId === ceo.id || u.id === ceo.id) : users;
  const pageCount = faker.number.int({ min: 4, max: 8 });
  const topLevelPages = [];

  for (let i = 0; i < pageCount; i++) {
    const author = faker.helpers.arrayElement(contributors);
    const createdAt = faker.date.past({ years: 1 });
    const updatedAt = faker.date.between({ from: createdAt, to: new Date() });
    const isChild = topLevelPages.length > 0 && faker.datatype.boolean(0.35);
    const parentId = isChild ? faker.helpers.arrayElement(topLevelPages) : null;
    const title = isChild
      ? `${faker.helpers.arrayElement(PAGE_TITLES)} - ${faker.word.words(2)}`
      : faker.helpers.arrayElement(PAGE_TITLES);
    const updatedByRow = faker.datatype.boolean(0.3) ? faker.helpers.arrayElement(contributors) : author;

    const currentPageId = pageId++;
    if (!isChild) topLevelPages.push(currentPageId);

    statements.push(
      `INSERT INTO pages (id, space_id, parent_page_id, title, body, author_id, updated_by, created_at, updated_at) VALUES (${currentPageId}, ${spaceId}, ${parentId ?? "NULL"}, ${sqlStr(title)}, ${sqlStr(faker.lorem.paragraphs({ min: 2, max: 5 }, "\n\n"))}, ${author.id}, ${updatedByRow.id}, ${sqlStr(createdAt.toISOString())}, ${sqlStr(updatedAt.toISOString())});`
    );

    if (faker.datatype.boolean(0.4)) {
      const versionCount = faker.number.int({ min: 1, max: 2 });
      for (let v = 0; v < versionCount; v++) {
        statements.push(
          `INSERT INTO page_versions (id, page_id, body, edited_by, edited_at) VALUES (${versionId++}, ${currentPageId}, ${sqlStr(faker.lorem.paragraphs({ min: 1, max: 3 }, "\n\n"))}, ${faker.helpers.arrayElement(contributors).id}, ${sqlStr(faker.date.between({ from: createdAt, to: updatedAt }).toISOString())});`
        );
      }
    }
  }

  spaceId++;
}

const sql = statements.join("\n") + "\n";
writeFileSync(OUT_PATH, sql, "utf8");
console.log(`Wrote ${statements.length} statements (${users.length} users, ${SPACES.length} spaces, ${pageId - 1} pages) to ${OUT_PATH}`);
