import { SignJWT, importPKCS8 } from "jose";
import type { Env } from "../env.js";

const ALG = "RS256";
const DEFAULT_KEY_ID = "flareid-key-1";

function currentKeyId(env: Env): string {
  return env.SIGNING_KEY_ID || DEFAULT_KEY_ID;
}

async function getSigningKey(env: Env) {
  if (!env.SIGNING_KEY_PKCS8) {
    throw new Error("SIGNING_KEY_PKCS8 is not configured - run `npm run keygen` and set the secret");
  }
  return importPKCS8(env.SIGNING_KEY_PKCS8, ALG);
}

export interface IdTokenClaims {
  sub: string;
  id: string;
  email: string;
  name: string;
  givenName: string;
  familyName: string;
  groups: string[];
  amr: string[];
  jobTitle: string;
  department: string;
  /** The manager's email, resolved at issuance time from their stable external_id reference. */
  managerEmail: string | null;
  nonce?: string;
}

/**
 * Builds the claim set shared by the id_token and /userinfo, matching the
 * shape Cloudflare Access's own OIDC integrations surface: top-level
 * id/email/name/given_name/family_name/groups/amr, plus HR attributes
 * (job_title/department/manager) so Zero Trust policies can match on them,
 * and a nested "custom" object carrying the same attributes (some Access
 * policy/claim mapping UIs expect custom attributes namespaced under "custom").
 */
export function buildClaims(claims: IdTokenClaims) {
  const attributes = {
    id: claims.id,
    email: claims.email,
    name: claims.name,
    given_name: claims.givenName,
    family_name: claims.familyName,
    groups: claims.groups,
    job_title: claims.jobTitle,
    department: claims.department,
    manager: claims.managerEmail,
  };
  return {
    ...attributes,
    amr: claims.amr,
    custom: attributes,
  };
}

export async function signIdToken(env: Env, clientId: string, claims: IdTokenClaims): Promise<string> {
  const key = await getSigningKey(env);
  const jwt = new SignJWT({
    ...buildClaims(claims),
    ...(claims.nonce ? { nonce: claims.nonce } : {}),
  })
    .setProtectedHeader({ alg: ALG, kid: currentKeyId(env) })
    .setIssuer(env.ISSUER_URL)
    .setAudience(clientId)
    .setSubject(claims.sub)
    .setIssuedAt()
    .setExpirationTime("10m");

  return jwt.sign(key);
}

/**
 * Publishes every currently-valid public key for /jwks.json (generated by
 * scripts/generate-keypair.mjs). Normally just the current key, but during a
 * rotation window both the current and previous keys are published so tokens
 * signed moments before the rotation remain verifiable until they expire.
 */
export function getPublicJwks(env: Env) {
  const current = JSON.parse(env.SIGNING_PUBLIC_JWK) as Record<string, unknown>;
  const keys = [{ ...current, kid: currentKeyId(env), use: "sig", alg: ALG }];

  if (env.SIGNING_PUBLIC_JWK_PREVIOUS && env.SIGNING_KEY_ID_PREVIOUS) {
    const previous = JSON.parse(env.SIGNING_PUBLIC_JWK_PREVIOUS) as Record<string, unknown>;
    keys.push({ ...previous, kid: env.SIGNING_KEY_ID_PREVIOUS, use: "sig", alg: ALG });
  }

  return keys;
}
