#!/usr/bin/env node
// Generates deterministic seed SQL for the Relay (inbox + calendar) demo app's
// D1 database. Derives `users` directly from hr-app's already-generated seed
// data (same ids/emails/manager hierarchy), then generates a personal inbox
// and calendar per person with @faker-js/faker.
//
// Usage: node shared/seed/generate-seed.mjs > api/migrations/0002_seed.sql

import { faker } from "@faker-js/faker";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

faker.seed(242); // deterministic output across runs

const __dirname = dirname(fileURLToPath(import.meta.url));
const HR_SEED_PATH = resolve(__dirname, "../../../hr-app/api/migrations/0002_seed.sql");
const OUT_PATH = resolve(__dirname, "../../api/migrations/0002_seed.sql");

const hrSeedSql = readFileSync(HR_SEED_PATH, "utf8");

function sqlStr(value) {
  if (value === null || value === undefined) return "NULL";
  return `'${String(value).replace(/'/g, "''")}'`;
}

const SQL_STRING = "'((?:[^']|'')*)'";
function unescapeSql(value) {
  return value.replace(/''/g, "'");
}

// --- Parse employees -> users ---
const employeeRowRegex = new RegExp(
  `INSERT INTO employees \\([^)]*\\) VALUES \\((\\d+), ${SQL_STRING}, ${SQL_STRING}, ${SQL_STRING}, ${SQL_STRING}, ${SQL_STRING}, (\\d+), (NULL|\\d+),`,
  "g"
);

const users = [];
for (const match of hrSeedSql.matchAll(employeeRowRegex)) {
  const [, id, , firstName, lastName, email, jobTitle, , managerId] = match;
  users.push({
    id: Number(id),
    firstName: unescapeSql(firstName),
    lastName: unescapeSql(lastName),
    email: unescapeSql(email).replace(/@aihorizon-demo\.com$/, "@company.com"),
    jobTitle: unescapeSql(jobTitle),
    managerId: managerId === "NULL" ? null : Number(managerId),
  });
}

if (users.length === 0) {
  console.error(`No employees parsed from ${HR_SEED_PATH} - has the hr-app seed been generated?`);
  process.exit(1);
}

const statements = [];
statements.push("-- Auto-generated by shared/seed/generate-seed.mjs. Do not edit by hand.");

for (const u of users) {
  statements.push(
    `INSERT INTO users (id, first_name, last_name, email, job_title, manager_id) VALUES (${u.id}, ${sqlStr(u.firstName)}, ${sqlStr(u.lastName)}, ${sqlStr(u.email)}, ${sqlStr(u.jobTitle)}, ${u.managerId ?? "NULL"});`
  );
}

const EXTERNAL_DOMAINS = ["acme-vendor.com", "bigclient.io", "partnerfirm.com", "gmail.com"];
const SUBJECTS = [
  "Re: Q3 planning doc",
  "Quick question about the proposal",
  "Meeting notes from yesterday",
  "Invoice #{n} attached",
  "Following up on our call",
  "Weekly status update",
  "Can we reschedule?",
  "Great meeting you at the conference",
  "Contract renewal - action needed",
  "Thanks for your help!",
  "Budget approval request",
  "New hire onboarding checklist",
  "Server maintenance window this weekend",
  "Customer feedback summary",
  "Your expense report has been approved",
];

function randomSubject() {
  const s = faker.helpers.arrayElement(SUBJECTS);
  return s.includes("{n}") ? s.replace("{n}", String(faker.number.int({ min: 1000, max: 9999 }))) : s;
}

let emailId = 1;
for (const u of users) {
  const emailCount = faker.number.int({ min: 20, max: 40 });
  for (let i = 0; i < emailCount; i++) {
    const folder = faker.helpers.weightedArrayElement([
      { value: "inbox", weight: 6 },
      { value: "sent", weight: 3 },
      { value: "archive", weight: 2 },
    ]);
    const receivedAt = faker.date.recent({ days: 45 });
    const threadId = `thread-${u.id}-${faker.string.alphanumeric(8)}`;
    const subject = randomSubject();
    const body = faker.lorem.paragraphs({ min: 1, max: 3 }, "\n\n");

    let fromName, fromEmail, toEmail;
    if (folder === "sent") {
      fromName = `${u.firstName} ${u.lastName}`;
      fromEmail = u.email;
      const recipient = faker.datatype.boolean(0.6)
        ? faker.helpers.arrayElement(users.filter((o) => o.id !== u.id))
        : null;
      toEmail = recipient ? recipient.email : faker.internet.email({ provider: faker.helpers.arrayElement(EXTERNAL_DOMAINS) }).toLowerCase();
    } else {
      const internalSender = faker.datatype.boolean(0.5)
        ? faker.helpers.arrayElement(users.filter((o) => o.id !== u.id))
        : null;
      if (internalSender) {
        fromName = `${internalSender.firstName} ${internalSender.lastName}`;
        fromEmail = internalSender.email;
      } else {
        fromName = faker.person.fullName();
        fromEmail = faker.internet.email({ firstName: fromName.split(" ")[0], provider: faker.helpers.arrayElement(EXTERNAL_DOMAINS) }).toLowerCase();
      }
      toEmail = u.email;
    }

    const isRead = folder === "sent" ? 1 : faker.datatype.boolean(0.7) ? 1 : 0;

    statements.push(
      `INSERT INTO emails (id, owner_id, thread_id, from_name, from_email, to_email, subject, body, folder, is_read, received_at) VALUES (${emailId++}, ${u.id}, ${sqlStr(threadId)}, ${sqlStr(fromName)}, ${sqlStr(fromEmail)}, ${sqlStr(toEmail)}, ${sqlStr(subject)}, ${sqlStr(body)}, ${sqlStr(folder)}, ${isRead}, ${sqlStr(receivedAt.toISOString())});`
    );
  }
}

const MEETING_TITLES = [
  "1:1 sync",
  "Sprint planning",
  "Quarterly business review",
  "Customer check-in",
  "All-hands",
  "Design review",
  "Budget review",
  "Interview debrief",
  "Onboarding session",
  "Vendor call",
  "Team retro",
  "Roadmap discussion",
];
const LOCATIONS = ["Conference Room A", "Conference Room B", "Zoom", "Google Meet", "HQ - 4th Floor", "Remote"];

let meetingId = 1;
const MEETING_COUNT = 220;
for (let i = 0; i < MEETING_COUNT; i++) {
  const organizer = faker.helpers.arrayElement(users);
  const attendeeCount = faker.number.int({ min: 1, max: 3 });
  const attendeePool = users.filter((u) => u.id !== organizer.id);
  const attendees = faker.helpers.arrayElements(attendeePool, Math.min(attendeeCount, attendeePool.length));

  const start = faker.date.between({ from: "2026-08-15", to: "2026-10-15" });
  const durationMinutes = faker.helpers.arrayElement([30, 30, 60, 60, 90]);
  const end = new Date(start.getTime() + durationMinutes * 60_000);

  statements.push(
    `INSERT INTO meetings (id, title, description, location, organizer_id, start_time, end_time) VALUES (${meetingId}, ${sqlStr(faker.helpers.arrayElement(MEETING_TITLES))}, ${sqlStr(faker.lorem.sentence())}, ${sqlStr(faker.helpers.arrayElement(LOCATIONS))}, ${organizer.id}, ${sqlStr(start.toISOString())}, ${sqlStr(end.toISOString())});`
  );

  // Organizer is implicitly an accepted attendee of their own meeting.
  statements.push(
    `INSERT INTO meeting_attendees (meeting_id, user_id, response_status) VALUES (${meetingId}, ${organizer.id}, 'accepted');`
  );
  for (const a of attendees) {
    const status = faker.helpers.weightedArrayElement([
      { value: "accepted", weight: 5 },
      { value: "tentative", weight: 2 },
      { value: "needs_action", weight: 2 },
      { value: "declined", weight: 1 },
    ]);
    statements.push(
      `INSERT INTO meeting_attendees (meeting_id, user_id, response_status) VALUES (${meetingId}, ${a.id}, ${sqlStr(status)});`
    );
  }

  meetingId++;
}

const sql = statements.join("\n") + "\n";
writeFileSync(OUT_PATH, sql, "utf8");
console.log(`Wrote ${statements.length} statements (${users.length} users, ${emailId - 1} emails, ${meetingId - 1} meetings) to ${OUT_PATH}`);
